import { extendTheme } from 'native-base';
import { globalStyles } from './globalStyles';

export const PRIMARY_COLOR = '#000000';

export const globals = globalStyles(PRIMARY_COLOR);

// generated by https://materialpalettes.com/
export const theme = extendTheme({
  colors: {
    primary: {
      50: '#9d9d9d',
      100: '#7b7b7b',
      200: '#555555',
      300: '#434343',
      400: '#262626',
      500: '#000000',
      600: '#000000',
      700: '#000000',
      800: '#000000',
      900: '#000000',
    },
  },
  fonts: {
    body: 'Inter',
    heading: 'Inter_bold',
    monospace: 'Courier, Monaco, monospace',
  },
  components: {
    Text: {
      baseStyle: {
        fontSize: 'md',
      },
    },
    Checkbox: {
      baseStyle: {
        _text: {
          fontSize: 'md',
        },
      },
    },
    Button: {
      baseStyle: {
        paddingTop: 3,
        paddingBottom: 3,
        _text: {
          fontWeight: 'bold',
        },
      },
      defaultProps: {
        size: 'md',
        _hover: {
          bg: 'primary.300',
          _text: {
            color: 'white',
          },
        },
        _pressed: {
          bg: 'primary.300',
          _text: {
            color: 'white',
          },
        },
      },
    },
    Input: {
      defaultProps: {
        size: 'sm',
        fontSize: 'md',
        fontFamily: 'monospace',
      },
    },
    TextArea: {
      defaultProps: {
        size: 'sm',
        fontSize: 'md',
        fontFamily: 'monospace',
      },
    },
    Heading: {
      baseStyle: {
        color: 'primary.500',
      },
    },
  },
  config: {
    // Changing initialColorMode to 'dark'
    initialColorMode: 'light',
  },
});
