import { extendTheme } from 'native-base';
import { Ionicons } from '@expo/vector-icons';
import { globalStyles } from './globalStyles';

export * from './components';

export const PRIMARY_COLOR = '#07d6a0';

export const globals = globalStyles(PRIMARY_COLOR);

// generated by https://angular-md-color.com/#/
export const theme = extendTheme({
  colors: {
    primary: {
      50: '#63fad2',
      100: '#4af9cb',
      200: '#31f8c4',
      300: '#19f7bd',
      400: '#08efb2',
      500: '#07d6a0',
      600: '#06bd8e',
      700: '#05a57b',
      800: '#058c69',
      900: '#047356',
    },
  },
  fonts: {
    body: '"Inter", sans-serif',
    heading: 'Inter_bold, sans-serif',
    monospace: 'Courier, Monaco, monospace',
  },
  components: {
    Text: {
      baseStyle: {
        fontSize: 'md',
      },
    },
    Checkbox: {
      baseStyle: {
        _text: {
          fontSize: 'md',
        },
      },
    },
    Button: {
      baseStyle: {
        borderRadius: 'sm',
        paddingTop: 3,
        paddingBottom: 3,
        _text: {
          fontWeight: 'bold',
        },
      },
      defaultProps: {
        size: 'md',
        _hover: {
          bg: 'primary.500',
          _text: {
            color: 'white',
          },
        },
        _pressed: {
          bg: 'primary.100',
          _text: {
            color: 'white',
          },
        },
      },
    },
    Input: {
      defaultProps: {
        size: 'sm',
        fontSize: 'md',
        fontFamily: 'monospace',
      },
    },
    TextArea: {
      defaultProps: {
        size: 'sm',
        fontSize: 'md',
        fontFamily: 'monospace',
      },
    },
    Heading: {
      baseStyle: {
        color: 'primary.500',
      },
    },
    ModalCloseButton: {
      baseStyle: {
        _icon: {
          as: Ionicons,
          borderRadius: 'full',
          color: 'white',
          name: 'close',
          size: 'xs',
        },
        _hover: {
          bg: 'gray.900:alpha.100',
        },
        _focusVisible: {
          bg: 'gray.900:alpha.100',
        },
        _pressed: {
          bg: 'gray.900:alpha.100',
        },
        bg: 'gray.900:alpha.50',
        borderRadius: 'full',
        p: 1,
        variant: 'unstyled',
      },
    },
  },
  config: {
    // Changing initialColorMode to 'dark'
    initialColorMode: 'light',
  },
});
